### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by kellytk** [cswindle/caesium#4]
Alternative registries being easy to run is important for at least Rust development if not the tech's wider ecosystem.  Is this project actively maintained?

**Comment by gilescope** [comment]
I think you can guess the answer to that one... but also looking for this kind of thing. Do we start from here or is there a better starting point?

**Comment by kellytk** [comment]
@gilescope I've since found https://github.com/Hirevo/alexandrie and intend on using it.
